### ISSUE TITLE
Preparations for GNOME 3.25/3.26 and Arc Menu v15

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#141]
@LinxGem33 
As of today [1], Ubuntu 17.10 is now using GNOME 3.25. So it's time to create a github issue to for the preparations for the GNOME 3.26 release on 13. September [2].

And yes, of course Arc-Menu (v14) works on the Ubuntu 17.10 development branch! I mean we are professionals, aren't we? Here is the proof:

![virtualbox_ubuntu-17 10_01_09_2017_07_14_07](https://user-images.githubusercontent.com/649340/29956404-17f03f18-8ee7-11e7-9126-7f7b8263bd1d.png)

Anyways, we need to update the metadata.json file soon and the Arc-Menu on extensions.gnome.org, so Arc-Menu is ready for GNOME 3.26 and Ubuntu 17.10 :-).

[1] https://plus.google.com/+WorldofGnomeOrg/posts/9zR264vFQsQ
[2] https://wiki.gnome.org/ThreePointTwentyfive#Schedule

**PS:**
@jbicha Keep up the good work and keep backporting GNOME 3.25 to Debian Sid :smile:!

**Comment by lexruee** [comment]
I tested Arc-Menu on GNOME 3.25/Ubuntu 17.10 and discovered some warnings such as:
* `Too many arguments to method Clutter.Actor.add_child: expected 1, got 2`
* `That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.`

Fortunately these errors & warnings are not too difficult to fix. For the next release, I would also like to fix the bug https://github.com/LinxGem33/Arc-Menu/issues/95 and depending on my spare time I will also try to fix the bug https://github.com/LinxGem33/Arc-Menu/issues/131.

Some logs:
[1] http://paste.debian.net/983974
[2] http://paste.debian.net/983968

**Comment by LinxGem33** [comment]
@lexruee 

ive added the version bump for the metadata.jason and ill also look into the issues you listed above.
